version: '2'
services:
    sakuranekoj2ee-app:
        image: sakuranekoj2ee
            - sakuranekoj2ee-mariadb:mariadb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/sakuranekoj2ee
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sakuranekoj2ee-mariadb:
        extends:
            file: mariadb.yml
            service: sakuranekoj2ee-mariadb
