version: '2'
services:
    sakuranekoj2ee-mariadb:
        container_name: sakuranekoj2ee-mariadb
        image: mariadb:10.1.14
        # volumes:
        #     - ~/volumes/jhipster/SakuraNekoJ2ee/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=sakuranekoj2ee
        ports:
            - 3306:3306
